### ISSUE TITLE
What is npm for?

### ISSUE THREAD

**Issue by ajukraine** [kuzm1ch/docker-stop-sites#2]
I was browsing the shell script, and am wondering, what is npm for?

https://github.com/kuzm1ch/docker-stop-sites/blob/main/script.sh#L7

**Comment by CherniakYura** [comment]
npm is a package manager , if you want more info please google

**Comment by dannycrief** [comment]
npm is a node package manager

**Comment by TrueLecter** [comment]
It starts rendertron main process, which is then called by `curl` later in for loop

**Comment by Slayv** [comment]
> It starts rendertron main process, which is then called by `curl` later in for loop

Might be useful to put it as a comment because it's not really common knowledge

**Comment by ajukraine** [comment]
Thanks @TrueLecter it wasn't really obvious what npm does in this case. Thanks
