### ISSUE TITLE
Docker without sudo

### ISSUE THREAD

**Issue by vovagorodok** [kuzm1ch/docker-stop-sites#3]
Hi gujs,

Will be nice add to readme:
https://docs.docker.com/engine/install/linux-postinstall/

```
sudo groupadd docker
sudo usermod -aG docker $USER
```

in order to run docker without sudo. Litle bit safety

**Comment by vovagorodok** [comment]
Pull request created:
https://github.com/kuzm1ch/docker-stop-sites/pull/4

**Comment by kuzm1ch** [comment]
thanks for PR, closed
